# Generated by Django 4.1 on 2022-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="Freakin' Blog", max_length=255),
        ),
    ]
